<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MX-IT01120" name="Default test" tests="11" failures="1" timestamp="4 Apr 2018 22:33:01 GMT" time="5.345" errors="0">
  <testcase name="getCommentsTest" time="1.808" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="postByIdTest" time="0.623" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="postByIdTest" time="0.21" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="postByIdTest" time="0.237" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="schemaValidationTest" time="0.685" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="schemaValidationTest" time="0.275" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="schemaValidationTest" time="0.176" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="schemaValidationTest" time="0.483" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="schemaValidationTest" time="0.179" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="schemaValidationTest" time="0.162" classname="com.automation.rest.test.RestAssuredTests"/>
  <testcase name="statusCodeValidation" time="0.45" classname="com.automation.rest.test.RestAssuredTests">
    <failure type="java.lang.AssertionError" message="expected [100] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [100] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.automation.rest.test.RestAssuredTests.statusCodeValidation(RestAssuredTests.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- statusCodeValidation -->
</testsuite> <!-- Default test -->
